ALTER TABLE app_user COMMENT = '前台用户账号表';
ALTER TABLE app_user MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID';
ALTER TABLE app_user MODIFY avatar_url VARCHAR(255) COMMENT '头像图片地址';
ALTER TABLE app_user MODIFY bio VARCHAR(500) COMMENT '个人简介';
ALTER TABLE app_user MODIFY blacklisted BIT(1) COMMENT '是否被平台限制';
ALTER TABLE app_user MODIFY blacklist_reason VARCHAR(255) COMMENT '账号限制原因';
ALTER TABLE app_user MODIFY city VARCHAR(255) COMMENT '常驻城市';
ALTER TABLE app_user MODIFY created_at DATETIME(6) COMMENT '注册时间';
ALTER TABLE app_user MODIFY nickname VARCHAR(255) COMMENT '站内展示昵称';
ALTER TABLE app_user MODIFY role VARCHAR(255) COMMENT '用户角色：USER 普通用户，SUPER_ADMIN 超级管理员';
ALTER TABLE app_user MODIFY username VARCHAR(255) COMMENT '登录用户名';
ALTER TABLE app_user MODIFY phone VARCHAR(255) COMMENT '登录手机号';
ALTER TABLE app_user MODIFY password_hash VARCHAR(255) COMMENT 'BCrypt 密码哈希';
ALTER TABLE app_user MODIFY password_salt VARCHAR(255) COMMENT '预留密码盐字段，BCrypt 已内置盐';
ALTER TABLE app_user MODIFY last_login_at DATETIME(6) COMMENT '最近登录时间';

ALTER TABLE pet_category COMMENT = '宠物分类表';
ALTER TABLE pet_category MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类ID';
ALTER TABLE pet_category MODIFY description VARCHAR(255) COMMENT '分类说明';
ALTER TABLE pet_category MODIFY image_url VARCHAR(255) COMMENT '分类封面图片地址';
ALTER TABLE pet_category MODIFY name VARCHAR(255) COMMENT '分类名称';
ALTER TABLE pet_category MODIFY tags VARCHAR(255) COMMENT '分类标签，逗号分隔';

ALTER TABLE pet COMMENT = '宠物百科资料表';
ALTER TABLE pet MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '宠物资料ID';
ALTER TABLE pet MODIFY age VARCHAR(255) COMMENT '年龄描述';
ALTER TABLE pet MODIFY age_range VARCHAR(255) COMMENT '年龄阶段';
ALTER TABLE pet MODIFY breed VARCHAR(255) COMMENT '品种';
ALTER TABLE pet MODIFY care_notes VARCHAR(600) COMMENT '饲养注意事项';
ALTER TABLE pet MODIFY category VARCHAR(255) COMMENT '所属分类';
ALTER TABLE pet MODIFY city VARCHAR(255) COMMENT '所在城市';
ALTER TABLE pet MODIFY dewormed BIT(1) COMMENT '是否已驱虫';
ALTER TABLE pet MODIFY gender VARCHAR(255) COMMENT '性别';
ALTER TABLE pet MODIFY health_info VARCHAR(255) COMMENT '健康摘要';
ALTER TABLE pet MODIFY health_records VARCHAR(1000) COMMENT '健康记录';
ALTER TABLE pet MODIFY image_url VARCHAR(255) COMMENT '主图地址';
ALTER TABLE pet MODIFY image_urls VARCHAR(2000) COMMENT '图片地址列表，逗号分隔';
ALTER TABLE pet MODIFY name VARCHAR(255) COMMENT '宠物名称';
ALTER TABLE pet MODIFY neutered BIT(1) COMMENT '是否已绝育';
ALTER TABLE pet MODIFY owner_name VARCHAR(255) COMMENT '资料维护人或主人名称';
ALTER TABLE pet MODIFY personality VARCHAR(255) COMMENT '性格特点';
ALTER TABLE pet MODIFY price DECIMAL(19,2) COMMENT '参考价格';
ALTER TABLE pet MODIFY status VARCHAR(255) COMMENT '资料状态';
ALTER TABLE pet MODIFY vaccinated BIT(1) COMMENT '是否已免疫';

ALTER TABLE market_post COMMENT = '交易帖子表';
ALTER TABLE market_post MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '交易帖ID';
ALTER TABLE market_post MODIFY audit_status VARCHAR(255) COMMENT '审核状态';
ALTER TABLE market_post MODIFY author VARCHAR(255) COMMENT '发布人昵称';
ALTER TABLE market_post MODIFY category VARCHAR(255) COMMENT '宠物或用品分类';
ALTER TABLE market_post MODIFY city VARCHAR(255) COMMENT '交易城市';
ALTER TABLE market_post MODIFY contact VARCHAR(255) COMMENT '联系渠道，固定为站内私信';
ALTER TABLE market_post MODIFY created_at DATETIME(6) COMMENT '发布时间';
ALTER TABLE market_post MODIFY description VARCHAR(1000) COMMENT '帖子详情';
ALTER TABLE market_post MODIFY image_url VARCHAR(255) COMMENT '主图地址';
ALTER TABLE market_post MODIFY image_urls VARCHAR(2000) COMMENT '图片地址列表，逗号分隔';
ALTER TABLE market_post MODIFY price DECIMAL(19,2) COMMENT '价格或预算';
ALTER TABLE market_post MODIFY status VARCHAR(255) COMMENT '交易状态';
ALTER TABLE market_post MODIFY title VARCHAR(255) COMMENT '帖子标题';
ALTER TABLE market_post MODIFY type VARCHAR(255) COMMENT '交易类型：售卖、领养、互换、闲置、寄养等';

ALTER TABLE moment COMMENT = '宠物日常动态表';
ALTER TABLE moment MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '动态ID';
ALTER TABLE moment MODIFY audit_status VARCHAR(255) COMMENT '审核状态';
ALTER TABLE moment MODIFY author VARCHAR(255) COMMENT '发布人昵称';
ALTER TABLE moment MODIFY category VARCHAR(255) COMMENT '动态分类';
ALTER TABLE moment MODIFY city VARCHAR(255) COMMENT '发布城市';
ALTER TABLE moment MODIFY content VARCHAR(1000) COMMENT '动态正文';
ALTER TABLE moment MODIFY created_at DATETIME(6) COMMENT '发布时间';
ALTER TABLE moment MODIFY image_url VARCHAR(255) COMMENT '主图地址';
ALTER TABLE moment MODIFY image_urls VARCHAR(2000) COMMENT '图片地址列表，逗号分隔';
ALTER TABLE moment MODIFY likes INT COMMENT '点赞数';
ALTER TABLE moment MODIFY pet_name VARCHAR(255) COMMENT '宠物名称';

ALTER TABLE moment_comment COMMENT = '宠物日常评论表';
ALTER TABLE moment_comment MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID';
ALTER TABLE moment_comment MODIFY author VARCHAR(255) COMMENT '评论人昵称';
ALTER TABLE moment_comment MODIFY content VARCHAR(500) COMMENT '评论内容';
ALTER TABLE moment_comment MODIFY created_at DATETIME(6) COMMENT '评论时间';
ALTER TABLE moment_comment MODIFY moment_id BIGINT COMMENT '所属动态ID';

ALTER TABLE post_favorites COMMENT = '交易帖收藏表';
ALTER TABLE post_favorites MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '收藏ID';
ALTER TABLE post_favorites MODIFY created_at DATETIME(6) COMMENT '收藏时间';
ALTER TABLE post_favorites MODIFY post_id BIGINT NOT NULL COMMENT '交易帖ID';
ALTER TABLE post_favorites MODIFY user_nickname VARCHAR(255) NOT NULL COMMENT '收藏人昵称';

ALTER TABLE private_message_threads COMMENT = '站内私信会话表';
ALTER TABLE private_message_threads MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '会话ID';
ALTER TABLE private_message_threads MODIFY created_at DATETIME(6) COMMENT '会话创建时间';
ALTER TABLE private_message_threads MODIFY post_id BIGINT COMMENT '关联交易帖ID';
ALTER TABLE private_message_threads MODIFY post_title VARCHAR(255) COMMENT '关联交易帖标题';
ALTER TABLE private_message_threads MODIFY recipient VARCHAR(255) COMMENT '接收人昵称';
ALTER TABLE private_message_threads MODIFY starter VARCHAR(255) COMMENT '发起人昵称';
ALTER TABLE private_message_threads MODIFY updated_at DATETIME(6) COMMENT '最近消息时间';

ALTER TABLE private_messages COMMENT = '站内私信消息表';
ALTER TABLE private_messages MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '消息ID';
ALTER TABLE private_messages MODIFY content VARCHAR(1000) COMMENT '消息内容';
ALTER TABLE private_messages MODIFY created_at DATETIME(6) COMMENT '发送时间';
ALTER TABLE private_messages MODIFY read_by_recipient BIT(1) COMMENT '接收方是否已读';
ALTER TABLE private_messages MODIFY sender VARCHAR(255) COMMENT '发送人昵称';
ALTER TABLE private_messages MODIFY thread_id BIGINT COMMENT '所属会话ID';

ALTER TABLE trade_intents COMMENT = '交易意向表';
ALTER TABLE trade_intents MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '交易意向ID';
ALTER TABLE trade_intents MODIFY created_at DATETIME(6) COMMENT '提交时间';
ALTER TABLE trade_intents MODIFY message VARCHAR(600) COMMENT '意向说明';
ALTER TABLE trade_intents MODIFY owner VARCHAR(255) COMMENT '帖子发布人昵称';
ALTER TABLE trade_intents MODIFY post_id BIGINT COMMENT '交易帖ID';
ALTER TABLE trade_intents MODIFY post_title VARCHAR(255) COMMENT '交易帖标题';
ALTER TABLE trade_intents MODIFY requester VARCHAR(255) COMMENT '意向提交人昵称';
ALTER TABLE trade_intents MODIFY status VARCHAR(255) COMMENT '意向状态';
ALTER TABLE trade_intents MODIFY updated_at DATETIME(6) COMMENT '状态更新时间';

ALTER TABLE content_reports COMMENT = '内容举报表';
ALTER TABLE content_reports MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '举报ID';
ALTER TABLE content_reports MODIFY created_at DATETIME(6) COMMENT '举报时间';
ALTER TABLE content_reports MODIFY handle_note VARCHAR(500) COMMENT '处理备注';
ALTER TABLE content_reports MODIFY handled_at DATETIME(6) COMMENT '处理时间';
ALTER TABLE content_reports MODIFY handled_by VARCHAR(255) COMMENT '处理人昵称';
ALTER TABLE content_reports MODIFY reason VARCHAR(500) COMMENT '举报原因';
ALTER TABLE content_reports MODIFY reporter VARCHAR(255) COMMENT '举报人昵称';
ALTER TABLE content_reports MODIFY status VARCHAR(255) COMMENT '举报状态';
ALTER TABLE content_reports MODIFY target_id BIGINT COMMENT '被举报内容ID';
ALTER TABLE content_reports MODIFY target_type VARCHAR(255) COMMENT '被举报内容类型：post 或 moment';

ALTER TABLE reference_option COMMENT = '基础枚举配置表';
ALTER TABLE reference_option MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '配置项ID';
ALTER TABLE reference_option MODIFY label VARCHAR(255) COMMENT '展示名称';
ALTER TABLE reference_option MODIFY option_type VARCHAR(255) COMMENT '配置类型';
ALTER TABLE reference_option MODIFY sort_order INT COMMENT '排序值';

ALTER TABLE region_area COMMENT = '省市区地区库表';
ALTER TABLE region_area MODIFY id BIGINT NOT NULL AUTO_INCREMENT COMMENT '地区ID';
ALTER TABLE region_area MODIFY level VARCHAR(255) COMMENT '地区层级：province、city、district';
ALTER TABLE region_area MODIFY name VARCHAR(255) COMMENT '地区名称';
ALTER TABLE region_area MODIFY parent_id BIGINT COMMENT '上级地区ID';
ALTER TABLE region_area MODIFY sort_order INT COMMENT '排序值';
