ALTER TABLE admin_user ADD COLUMN role VARCHAR(32) NOT NULL DEFAULT 'ADMIN' AFTER display_name;
ALTER TABLE admin_user ADD COLUMN permissions VARCHAR(1000) NULL AFTER role;

UPDATE admin_user
SET role = 'SUPER_ADMIN'
WHERE role = 'ADMIN';

ALTER TABLE admin_user MODIFY COLUMN role VARCHAR(32) NOT NULL COMMENT '管理员角色：SUPER_ADMIN/ADMIN';
ALTER TABLE admin_user MODIFY COLUMN permissions VARCHAR(1000) NULL COMMENT '管理员权限编码，逗号分隔';
